# Use a lightweight Python image
FROM ubuntu:20.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y wget gnupg curl && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y ./google-chrome-stable_current_amd64.deb && \
    apt-get install -y python3 python3-pip

# Install Python dependencies
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the Flask app code
COPY Scraper.py /app/Scraper.py
WORKDIR /app

# Expose the port Flask runs on
EXPOSE 5000

# Run the Flask app
CMD ["python3", "Scraper.py"]



